###########
# VCPrison
# Advanced prison system for VaultCraft (July 31, 2014)
# Authors:
#  Connor Hollasch
#  Nick Peterson
###########
name: VCPrison
version: 1.0
load: POSTWORLD
authors: [IModZombies4Fun, Tacticalsk8er]
softdepend: [VCUtils, VCEssentials]
main: net.vaultcraft.vcprison.VCPrison